### ISSUE TITLE
I have applied the 7.5 with the above script

### ISSUE THREAD

**Issue by anand5555** [JESWINKNINAN/upgrade-openssh-7.5p1-centos#1]
I have applied the 7.5 with the above script. But it still show below packages i have restarted ssh service and rebooted the instance and it still show below o/p.

openssh-6.6.1p1-35.el7_3.x86_64
openssh-clients-6.6.1p1-35.el7_3.x86_64
openssh-server-6.6.1p1-35.el7_3.x86_64

can you help me how do i verify that its installed ?

Note : below is the success message when i run the shell script (i have installed all the dependencies while running the script)
/bin/install -c -m 644 ssh-pkcs11-helper.8.out /usr/local/share/man/man8/ssh-pkc                                                                                                                                                             s11-helper.8
if [ ! -d /usr/local/etc ]; then \
        ./mkinstalldirs /usr/local/etc; \
fi
/usr/local/etc/ssh_config already exists, install will not overwrite
/usr/local/etc/sshd_config already exists, install will not overwrite
/usr/local/etc/moduli already exists, install will not overwrite
/usr/local/sbin/sshd -t -f /usr/local/etc/sshd_config
New version upgrades as to lastest:
OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by jeswinkninan** [comment]
Please use ssh -V to find the version. Please download the rpm package manually and install those( rpm –ivh packagename.rpm) .Please run the same in a test server before going to prod.  Drop me a mail if you have any issues .
